services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    user: 5984:5984
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./data:/opt/couchdb/data
      - ./config:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    stop_grace_period: 20s
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      # Must be public URL reachable by notification receivers
      NTFY_BASE_URL: ${NTFY_BASE_URL}
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
    ports:
      - "5985:80"
    init: true
    stop_grace_period: 20s
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

  notifier:
    image: python:3.11-slim
    container_name: notifier
    depends_on:
      - couchdb
      - ntfy
    volumes:
      - ./notifier.py:/app/notifier.py
      - ./requirements.txt:/app/requirements.txt:ro
    environment:
      PYTHONUNBUFFERED: "1"
      COUCHDB_BASE_URL: ${COUCHDB_BASE_URL}
      COUCHDB_DATABASE: ${COUCHDB_DATABASE}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      # Command-line arguments for notifier.py:
      NTFY_BASE_URL: ${NTFY_BASE_URL}
      FILE_PATH: ${NOTIFIER_FILE_PATH} # Case-sensitive file path relative to vault root
      TOPIC_NAME: ${NOTIFIER_TOPIC_NAME}
    command: >
      sh -c "pip install --no-cache-dir -r /app/requirements.txt &&
             python /app/notifier.py $$NTFY_BASE_URL $$FILE_PATH $$TOPIC_NAME --loop"
    restart: always
